version: "3.7"
# from https://github.com/docker/awesome-compose/blob/master/official-documentation-samples/wordpress/README.md
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: '/usr/bin/mysql --user=foo --password=foo --execute "SHOW DATABASES;"'
      # test: "/usr/local/mysql/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal_quotation
    ports:
      - 3307:3306
      - 33060:33060

  wordpress:
    build: ./
    volumes:
      - ./wp_data:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins:delegated
      - ./themes:/var/www/html/wp-content/themes:delegated
    ports:
      - 8081:80
    restart: unless-stopped
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quotation.rule=PathPrefix(`/quotation`)"
      - "traefik.http.routers.quotation.priority=2"
      - "traefik.http.routers.quotation.entrypoints=websecure"
      - "traefik.http.routers.quotation.tls=true"
      - "traefik.http.routers.quotation.tls.certresolver=le-resolver"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.quotation-pages-router.priority=2"
    networks:
      - traefik_proxy
      - internal_quotation
    environment:
      WORDPRESS_DB_HOST: db:3307
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'DB_CHARSET', 'utf8mb4' );

volumes:
  db_data:
  wp_data:

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
  internal:
    name: internal_quotation
