<page backtop="5mm" backbottom="5mm" backleft="5mm" backright="5mm">
    <table style="width: 100%; border: 0;" id="cgv">
        <tr>
            <td style="width: 50%; padding-right:5mm;">
                <h2>CONDITIONS GÉNÉRALES DE VENTE</h2>
                <span>Mise à jour le 25/10/2020</span>
                <h3>ARTICLE 1 - OBJET ET CHAMP D'APPLICATION</h3>
                <p>Toute commande de produits et prestations de service implique l’acceptation sans réserve par l’acheteur et son adhésion pleine et entière aux présentes <strong>conditions générales de vente</strong> qui prévalent sur tout autre document de l’acheteur, et notamment sur toutes <strong>conditions générales d’achat</strong>, sauf accord dérogatoire exprès et préalable de notre société. Les présentes <strong>conditions générales de vente</strong> s’appliquent à toutes les ventes de produits par notre société sauf accord spécifique préalable à la commande convenu par écrit entre les parties. En conséquence, la passation d’une commande par un client emporte l’adhésion sans réserve, de ce dernier, aux présentes <strong>conditions générales de vente</strong>, sauf conditions particulières consenties par écrit par notre société à l’acquéreur. Toute modification apportée à nos conditions générales de vente seront applicables à toute nouvelle commande passée après modification de celles-ci, sans effet rétroactif.</p>
                <h3>ARTICLE 2 - PROPRIÉTÉ INTELLECTUELLE</h3>
                <p>Tous les documents techniques et d’informations remis à nos clients demeurent la propriété exclusive de notre société, seul titulaire des droits de propriété intellectuelle sur ces documents. Nos clients s’engagent à ne faire aucun usage de ces documents, susceptible de porter atteinte aux droits de propriété industrielle ou intellectuelle de notre société et s’engagent à ne les divulguer à aucun tiers.<br>Conformément au CPI (articles L. 121-1 à L. 121-9) ne seront cédés au client pour l’oeuvre décrite que les droits patrimoniaux explicitement énoncés dans les conditions de cession, à l’exclusion de tout autre, et ce, dans les limites y figurant également. Il est rappelé que le droit moral d’une création (comprenant entre autres droit au respect de l’oeuvre et droit au respect du nom) reste attaché à son auteur de manière perpétuelle et imprescriptible. Toute représentation ou reproduction intégrale ou partielle faite sans le consentement de l’auteur ou de ses ayants droit est illicite, et punie selon les lois relatives au délit de contrefaçon. Il en est de même pour la traduction, l’adaptation ou la transformation, l’arrangement ou la reproduction par un art ou un procédé quelconque (art. L. 122-4 du CPI).</p>
                <p>La totalité de la production et des droits s’y rapportant, objet de la présente commande, demeure la propriété entière et exclusive de notre société tant que les factures émises par celles-ci ne sont pas payées en totalité par la société cliente, à concurrence du montant global de la commande et des avenants éventuels conclus en cours de prestation.</p>
                <p>De façon corollaire, la société cliente deviendra propriétaire de fait des droits cédés à compter du règlement final et soldant de toutes les factures émises par notre société dans le cadre de la commande.<br>La livraison éventuelle des sources ou fichiers de travail relatifs à la présente commande ne se fera qu’en cas de nécessité induite par la stricte exploitation de l’oeuvre prévue dans les conditions de cession ou dans un avenant ultérieur.</p>
                <p>Notre société se réserve le droit de mentionner sa réalisation pour la société cliente comme référence et de citer des extraits textuels ou iconographiques des oeuvres concernées dans le strict cadre de ses démarches de prospection commerciale, de communication externe et de publicité. Toute réserve au droit de publicité de notre société devra être notifiée et négociée avant la signature du devis et mentionnée sur la facture.<br>Les modifications ou interprétations d’une création graphique ne peuvent être faites en aucun cas, sans le consentement du prestataire. La signature ne peut être supprimée sans l’accord du prestataire. Une idée proposée par le client ne constitue pas en soi une création.</p>
                <h3>ARTICLE 3 - COMMANDES</h3>
                <p>Par commande, il faut entendre tout ordre portant sur nos produits et prestations figurant à nos tarifs, et accepté par notre société, accompagné du paiement de l’acompte éventuellement prévu sur le bon de commande. Les commandes transmises à notre société sont irrévocables pour le client, sauf acceptation écrite de notre part. Toute demande de modification de la composition ou du volume d’une commande passée par un client ne pourra être prise en compte par notre société, que si la demande est faite par écrit y compris, courrier électronique et est parvenue à notre société, au plus tard 48 heures après réception par notre société de la commande initiale. En cas de modification de la commande par le client, notre société sera déliée des délais convenus pour son exécution. Tout commande sera validée après réception du bon de commande signé portant la mention « bon pour accord », accompagné de l’acompte exigé.</p>
                <h3>ARTICLE 4 - LIVRAISONS/EXÉCUTION</h3>
                <p>Les délais de livraison ne sont donnés qu’à titre informatif et indicatif ; ceux-ci dépendant notamment de la disponibilité des prestataires, des marchandises et des transporteurs et de l’ordre d’arrivée des commandes.<br>Notre société s’efforce de respecter les délais de livraison qu’elle indique à l’acceptation de la commande, en fonction du délai logistique de référence dans la profession, et à exécuter les commandes, sauf force majeure. Les retards de livraison ne peuvent donner lieu à aucune pénalité ou indemnité, ni motiver l’annulation de la commande.</p>
                <p>Tout retard par rapport aux délais indicatifs de livraison initialement prévus, ne saurait justifier une résiliation de la commande passée par le client et enregistrée par notre société.</p>
                <p>En cas de non-paiement intégral d’une facture venue à échéance, après mise en demeure restée sans effet dans les 7 jours, notre société se réserve la faculté de suspendre toute livraison en cours et/ou à venir. Toutes les commandes que nous acceptons d’exécuter le sont, compte tenu du fait que le client présente les garanties financières suffisantes, et qu’il réglera effectivement les sommes dues à leur échéance, conformément à la législation. Aussi, si notre société a des raisons sérieuses ou particulières de craindre des difficultés de paiement de la part du client à la date de la commande, ou postérieurement à celle-ci, notre société peut subordonner l’acceptation de la commande ou la poursuite de son exécution à un paiement comptant ou à la fourniture, par le client, de garanties au profit de notre société. En cas de refus par le client du paiement comptant, sans qu’aucune garantie suffisante ne soit proposée par ce dernier, notre société pourra refuser d’honorer la (les) commande(s) passée(s) et de livrer la marchandise ou la prestation concernée, sans que le client puisse arguer d'un</p>

            </td>
            <td style="width: 50%; padding-left:5mm;">
                <p>refus de vente injustifié, ou prétendre à une quelconque indemnité. Tout travail réalisé fera l’objet d’un Bon à Tirer.<br>Il est précisé concernant la validation de ce Bon à Tirer qu’il pourra être modifié au 2 fois au maximum. Toute modification supplémentaire entraînera une facturation supplémentaire.</p>
                <h3>ARTICLE 5 - TARIF - PRIX</h3>
                <p>Le tarif en vigueur peut être révisé à tout moment, après information préalable de nos clients. Toute modification tarifaire sera automatiquement applicable à la date indiquée sur le nouveau tarif. Nos prix seront déterminés en fonction de la prestation demandée. Ils s’entendent tou-jours en TTC. Ils sont calculés nets, sans escompte,et payables à la date mentionnée sur la facture. Pour les prix spécifiés par quantité, toute commande portant sur une quantité moindre, entraîne une modification du prix indiqué. Sauf accord contraire, les retards de livraison n’em-portent ni annulation, ni modification du contrat. Ils ne sauraient donner lieu à dommages et intérêts. Les clauses pénales figurant sur les papiers commerciaux de nos clients nous sont inopposables. Les délais d’exécution figurant dans une commande ne sont acceptés par notre société et ne l’engagent, que sous les conditions suivantes : respect par le client des condi-tions de paiement et de versement des acomptes, remise dans les délais impartis des élé-ments nécessaires à la réalisation du projet, absence de cas de force majeure.</p>
                <h3>ARTICLE 6 - FRAIS ANNEXES</h3>
                <p>Les éléments divers éventuellement nécessaires à la réalisation des prestations du Prestataire et ne relevant pas de ses offres ne sont pas compris dans les prix indiqués. Il s’agit par exemple des polices typographiques, des photographies ou illustrations issues de banques d’images. Il n’en va pas de même pour les frais d’impression et/ou d’hébergement internet. Le règlement de ceux-ci sont compris dans les tarifs.</p>
                <p>Le contenu textuel permettant la réalisation du produit devra être fourni par le Client. Les dé-placements nécessaires à la bonne réalisation du contrat pourront également être facturés au Client.</p>
                <h3>ARTICLE 7 - MODALITÉS DE RÈGLEMENT</h3>
                <p>Nos factures sont payables à la date d’échéance qui y figure. Seul l’encaissement effectif sera considéré comme valant complet paiement au sens des présentes « conditions générales de vente «. Les paiements pourront se faire aux moyens suivants : virement et chèque. Sauf délai de paiement supplémentaire convenu par accord entre les deux parties et figurant sur la fac-ture, le paiement s’effectue au plus tard au 30e jour suivant la date de facturation (C. Com. art. L. 441- 6, al. 2 modifié de la loi du 15 mai 2001). Tout retard de paiement pourra donner lieu à des pénalités de retard exigibles sans rappel, au taux de 10 % de la facture totale par mois de retard (lutte contre les retards de paiement/article 53 de la loi NRE), ainsi qu’à une indemnité forfaitaire de 40 euros€ (C. Com. art. D441-5). Un acompte de 50 % d’acompte pourra être demandé à la signature de la commande. Pour les projets ayant un délai de réalisation signifié par notre entreprise et validé par nos clients lors de la commande, supérieur à 5 mois, des acomptes intermédiaires pourront être exigé tous les 3 mois.</p>
                <h3>ARTICLE 8 - RESPONSABILITÉ</h3>
                <p>La société cliente assume pleine et entière responsabilité des choix réalisés en matière de contenus textuels et iconographiques figurant dans la réalisation livrée par notre société, tout comme de l’exploitation qui en sera faite, et notamment de la conformité de cette dernière avec les réglementations en vigueur. Elle assure également être propriétaire des droits né-cessaires à l’exploitation de tous les éléments créatifs textuels et iconographiques fournis par elle dans le cadre de sa mission, et garantit notre société contre toute plainte tierce relative à la violation des droits de ces éléments. Le Client s’engage à fournir des informations justes et sincères et s’engage à nous prévenir de tout changement concernant les données fournies et sera seul responsable des éventuels dysfonctionnements qui pourraient résulter d’infor-mations erronées. Le Client doit maintenir une adresse e-mail et une adresse postale valides</p>
                <h3>ARTICLE 9 - FORCE MAJEURE</h3>
                <p>Sont considérés comme cas de force majeure ou cas fortuits, les événements indépendants de la volonté des parties, qu’elles ne pouvaient raisonnablement être tenues de prévoir, et qu’elles ne pouvaient raisonnablement éviter ou surmonter, dans la mesure où leur survenance rend totalement impossible l’exécution des obligations. Dans de telles circonstances, notre société préviendra le client par écrit, notamment par courrier électronique, dans les 7 jours ouvrables de la date de survenance des événements, le contrat liant notre société et le client étant alors suspendu de plein droit sans indemnité, à compter de la date de survenance de l’événement. Si l’événement venait à durer plus de 30 jours à compter de la date de survenance de celui-ci, le contrat de vente conclu par notre société et son client pourra être résilié par la partie la plus diligente, sans qu’aucune des parties puisse prétendre à l’octroi de dommages et intérêts. Cette résiliation prendra effet à la date de première présentation de la lettre recom-mandée avec accusé de réception dénonçant ledit contrat de vente.</p>
                <h3>ARTICLE 10 - ATTRIBUTION DE JURIDICTION</h3>
                <p>L’élection de domicile est faite par notre société, à son siège social pour les litiges entre pro-fessionnels et suivra les règles judiciaires d’attribution de compétences pour les litiges nous opposant à des clients <strong>particuliers</strong>.</p>
                <h3>ARTICLE 11 - RENONCIATION</h3>
                <p>Le fait pour notre société de ne pas se prévaloir à un moment donné de l’une quelconque des clauses des présentes ne peut valoir renonciation à se prévaloir ultérieurement de ces mêmes clauses.</p>
                <h3>ARTICLE 12 - DROIT APPLICABLE</h3>
                <p>Toute question relative aux présentes <strong>conditions générales de vente</strong> ainsi qu’aux ventes qu’elles régissent, qui ne serait pas traitée par les présentes stipulations contractuelles, sera régie par la loi française à l’exclusion de tout autre droit, et à titre supplétif, par la convention de Vienne sur la vente internationale des marchandises.</p>

            </td>
        </tr>
    </table>
</page>